version: "3"
services:
  mc:
    image: itzg/minecraft-server
    container_name: # name
    hostname: minecraft
    ports:
      - 25565:25565/tcp
    environment:
      TZ: America/Chicago
      TYPE: "FABRIC"
      EULA: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: # "-1"
      DIFFICULTY: # "hard"
      SPAWN_PROTECTION: # "0"
      MOTD: # Message of the Day
      OPS: # Operators
      MEMORY: 10G
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
