version: "3.3"
services:
  grist:
    image: gristlabs/grist
    container_name: grist
    environment:
      - GRIST_SANDBOX_FLAVOR=gvisor
      - GRIST_PAGE_TITLE_SUFFIX=
      - GRIST_SESSION_SECRET=${GRIST_SESSION_SECRET}
    ports:
      - 8484:8484
    volumes:
      - ./data:/persist
    restart: unless-stopped
