version: "3"
services:
  mc:
    image: itzg/minecraft-server:java8
    container_name: # choose name
    hostname: Minecraft
    ports:
      - 25565:25565/tcp # might have to change port
    environment:
      TZ: America/Chicago
      TYPE: "AUTO_CURSEFORGE"
      EULA: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
      DIFFICULTY: # "hard"
      SPAWN_PROTECTION: # "0"
      ENABLE_COMMAND_BLOCK: # "TRUE"
      ALLOW_FLIGHT: # "TRUE" helps prevent against players behing kicked for lag spikes
      MOTD: # Message of the Day
      OPS: # Allowed Operators. Can be changed later
      MEMORY: 10G 
      VERSION: # minecraft version
      CF_API_KEY: # CurseForge API Key
      CF_PAGE_URL: # URL to mod pack
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data

